name: Build and Push to Registry

on:
    push:
        branches: [develop]
    workflow_dispatch:

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install dependencies
              run: npm install
              env:
                  CODEGEN_HASURA_ENDPOINT: ${{ secrets.CODEGEN_HASURA_ENDPOINT }}
                  CODEGEN_HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.CODEGEN_HASURA_GRAPHQL_ADMIN_SECRET }}

            - name: Generate GraphQL code
              run: npm run generate --ignore-errors
              env:
                  CODEGEN_HASURA_ENDPOINT: ${{ secrets.CODEGEN_HASURA_ENDPOINT }}
                  CODEGEN_HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.CODEGEN_HASURA_GRAPHQL_ADMIN_SECRET }}

            - name: Get version from package.json
              id: package-version
              run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Container Registry
              uses: docker/login-action@v2
              with:
                  registry: registry.crbgroup.xyz
                  username: ${{ vars.REG_USERNAME }}
                  password: ${{ secrets.REG_PASSWORD }}

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: ./Dockerfile.prod
                  push: true
                  build-args: |
                      NEXT_PUBLIC_CHAT_WS_URL=${{ vars.NEXT_PUBLIC_CHAT_WS_URL }}
                      NEXT_PUBLIC_HASURA_ENDPOINT=${{ vars.NEXT_PUBLIC_HASURA_ENDPOINT }}
                      NEXT_PUBLIC_HASURA_URL=${{ vars.NEXT_PUBLIC_HASURA_URL }}
                      NEXT_PUBLIC_HASURA_ADMIN_SECRET=${{ secrets.NEXT_PUBLIC_HASURA_ADMIN_SECRET }}
                      NEXT_PUBLIC_GHOST_API_URL=${{ vars.NEXT_PUBLIC_GHOST_API_URL }}
                      NEXT_PUBLIC_REQUEST_DEPOSIT=${{ vars.NEXT_PUBLIC_REQUEST_DEPOSIT }}
                      NEXT_PUBLIC_HASURA_ADMIN_SECRET=${{ secrets.NEXT_PUBLIC_HASURA_ADMIN_SECRET }}
                      NEXT_PUBLIC_GHOST_API_URL=${{ vars.NEXT_PUBLIC_GHOST_API_URL }}
                      NEXT_PUBLIC_API_KEY=${{ secrets.NEXT_PUBLIC_API_KEY }}
                      NEXT_PUBLIC_BASEURL_PAYMENT=${{ vars.NEXT_PUBLIC_BASEURL_PAYMENT }}
                      NEXT_PUBLIC_URL_CALLBACK=${{ vars.NEXT_PUBLIC_URL_CALLBACK }}
                      NEXT_PUBLIC_API_BASE_URL=${{ vars.NEXT_PUBLIC_API_BASE_URL }}
                      NEXT_PUBLIC_API_URL_DEV=${{ vars.NEXT_PUBLIC_API_URL_DEV }}
                      NEXT_PUBLIC_API_URL_PROD=${{ vars.NEXT_PUBLIC_API_URL_PROD }}

                      GHOST_API_KEY=${{ secrets.GHOST_API_KEY }}
                      CODEGEN_HASURA_GRAPHQL_ADMIN_SECRET=${{ secrets.CODEGEN_HASURA_GRAPHQL_ADMIN_SECRET }}
                      CODEGEN_HASURA_ENDPOINT=${{ secrets.CODEGEN_HASURA_ENDPOINT }}
                  tags: |
                      registry.crbgroup.xyz/shop3/user:latest
                      registry.crbgroup.xyz/shop3/user:v${{ steps.package-version.outputs.VERSION }}
