name: Build and Push Docker Image For Operator

on:
    push:
        branches:
            - develop
    pull_request:
        branches:
            - develop

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            # Thêm các bước setup Node.js, install và generate từ workflow shop3.chat
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install dependencies
              run: npm ci

            - name: Run generate
              run: npm run generate
              env:
                  VITE_CODEGEN_HASURA_ENDPOINT: ${{ secrets.VITE_CODEGEN_HASURA_ENDPOINT }}
                  VITE_CODEGEN_HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.VITE_CODEGEN_HASURA_GRAPHQL_ADMIN_SECRET }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Registry
              uses: docker/login-action@v3
              with:
                  registry: registry.crbgroup.xyz
                  username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
                  password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

            - name: Set Environment Variables
              run: |
                  echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
                  echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

            - name: Build and Push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: |
                      registry.crbgroup.xyz/shop3-operator:develop-${{ env.SHORT_SHA }}
                      registry.crbgroup.xyz/shop3-operator:develop-latest
                  build-args: |
                      VITE_CODEGEN_HASURA_ENDPOINT=${{ secrets.VITE_CODEGEN_HASURA_ENDPOINT }}
                  cache-from: type=registry,ref=registry.crbgroup.xyz/shop3-operator:develop-latest
                  cache-to: type=inline
